### PR TITLE
Added in extra checks for off hand watering can use

### PR DESCRIPTION
**Pull request by Lukatjee**

### CODE REVIEW

**Comment by NCBPFluffyBear** [comment]
Did you test this? Afaik it shouldn't work because you are checking a different event.

**Comment by Lukatjee** [comment]
It does: (video of fix)
https://cloud.lukatjee.eu/XePA1/KoRIBeya84.mp4
Original bugreport:
https://www.youtube.com/watch?v=WxaKKS3Dy3U&feature=youtu.be

**Comment by NCBPFluffyBear** [comment]
The issue is that it can be placed down on the ground when put in offhand

**Comment by Lukatjee** [comment]
Mkay, I'll check that out

**Comment by Lukatjee** [comment]
https://cloud.lukatjee.eu/XePA1/hufOCiHo93.mp4
https://cloud.lukatjee.eu/XePA1/CilItiNa70.mp4
I tried to reproduce the issue pointed out in your latest comment, but it seems it's not doing that (anymore)

**Pull request merged**
