### PR TITLE
Added soul soil to soul sand conversation to basic composter

### PR DESCRIPTION
**Pull request by jnsbndgz**
...

### CODE REVIEW

**Comment by NCBPFluffyBear** [comment]
Can recipes not be added the same way as ore crushers?

**Comment by jnsbndgz** [comment]
> Can recipes not be added the same way as ore crushers?

Nop... has no such method

image

This way works, as getDisplayRecipes() just returns the the list of recipes.

**Comment by NCBPFluffyBear** [comment]
Has this been tested?

**Comment by jnsbndgz** [comment]
I have tried it in game and it worked. Would be better to someone else check it as well.

**Comment by NCBPFluffyBear** [comment]
If it works for you it should be fine, not a complicated addition.

**Pull request merged**
